version: "3.8"

services:
  fastapi:
    container_name: fastapi-app
    build: .
    ports:
      - "${HOST_PORT}:8089"
    env_file:
      - .env
    volumes:
      - ${STORAGE_PATH}:${SOURCE_DIR}
    restart: always
